apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: slow
provisioner: kubernetes.io/aws-ebs
parameters:
  type: io1
  iopsPerGB: "10"
  fsType: ext4


#-----------------------------

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-sanchos
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    namespace: sanchos-claim
    name: pv-sanchos-claim
  hostPath:
    path: "/mnt/data"


